### ISSUE TITLE
Content for Manufacturer Software ID and Manufacturer Hardware ID in NMEA2000 data reversed

### ISSUE THREAD

**Issue by norbert-walter** [wellenvogel/esp32-nmea2000#25]
Content for Manufacturer Software ID and Manufacturer Hardware ID in NMEA2000 data reversed

**Comment by norbert-walter** [comment]
![grafik](https://user-images.githubusercontent.com/22027682/156527218-5af758f6-6682-4f04-87a1-944d470c1924.png)

**Comment by wellenvogel** [comment]
The mapping seems rather unclear in the N2K library. I did set up things this way due to length limits.
