### ISSUE TITLE
Shorter names for BoatValues by using XDR

### ISSUE THREAD

**Issue by norbert-walter** [wellenvogel/esp32-nmea2000#28]
Shorter names for BoatValues by using XDR. The BoatValue name begin with xdrTransducerName. The nme is to long for value selection in OBP pages. Better is xTransducerName.

**Comment by norbert-walter** [comment]
Solved.
I split the name and using the name after xdr.

**Comment by wellenvogel** [comment]
as agreed names will remain as they are
