### ISSUE TITLE
Save the last selected OBP60 page for a restart after power down

### ISSUE THREAD

**Issue by norbert-walter** [wellenvogel/esp32-nmea2000#29]
Save the last selected OBP60 page for a restart after power down. The MFD starts then with the old last page.

**Comment by wellenvogel** [comment]
This has to be done in the OBP60 code.

**Comment by norbert-walter** [comment]
preferences.begin("nvs", false);                          // Open nonvolatile storage (nvs)
  NodeAddress = preferences.getInt("LastNodeAddress", 32);  // Read stored last NodeAddress, default 32
  preferences.end();
