### ISSUE TITLE
my20220307: occasional time leaps on display and boatData

### ISSUE THREAD

**Issue by W-Geronius** [wellenvogel/esp32-nmea2000#32]
This issue was first seen on OBP60 display: see https://github.com/norbert-walter/esp32-nmea2000/issues/18
Occasional time leaps (-1 hour) can be observed also on DATA tab, like this (taken within 30 seconds):
![image](https://user-images.githubusercontent.com/18160302/157283146-90128d8f-4efb-4048-ad2c-168e464e73f7.png)
Examples extracted from api/boatDataString (previous to the screenshots) reveal a pattern:

```GPSD,formatDate,1,1938599,3,19059\n
GPST,formatTime,1,1938634,3,57726.02\n
2022-03-08 16:02:07        57727

GPSD,formatDate,1,1939659,3,19059\n
GPST,formatTime,1,1939705,3,57727.02\n
2022-03-08 16:02:09        57729

GPSD,formatDate,1,1941868,3,19059\n
GPST,formatTime,1,1941868,3,**54129**\n   **<--- time lapse !!!**
2022-03-08 16:02:10        57730

GPSD,formatDate,1,1942267,3,19059\n
GPST,formatTime,1,1942296,3,57730.02\n
2022-03-08 16:02:11        57731

GPSD,formatDate,1,1943274,3,19059\n
GPST,formatTime,1,1943297,3,57731.02\n
2022-03-08 16:02:12        57732
```

Whenever the value holds decimal places (always .02 !!), correct local time is displayed.
There is no pattern for decimal places missing, however, whenever they are absent UTC time is transmitted (and displayed).

Incoming GGA sentences look fine to me.  See attached inputdata from OP, boatDataString capture and configuration.
errors at 16:00:55, 16:01:40, 16:01:51, 16:02:10, 16:02:33, ... and many more

[[telnet 10.10.10.1]  (2022-03-08_160016)  raw OP out.log](https://github.com/wellenvogel/esp32-nmea2000/files/8208013/telnet.10.10.10.1.2022-03-08_160016.raw.OP.out.log)
[localhost@OBP60-GetBoatData.txt](https://github.com/wellenvogel/esp32-nmea2000/files/8208015/localhost%40OBP60-GetBoatData_VUser-Profile1_1.txt)
[config20220208.txt](https://github.com/wellenvogel/esp32-nmea2000/files/8208019/config20220208.txt)

**Comment by wellenvogel** [comment]
Your GLL data is jumping:
[2022-03-08 16:00:20]  $GPGLL,5043.9058,N,00700.4837,E,160020.020,A*3A
[2022-03-08 16:00:21]  $GNGLL,5043.9058,N,00700.4837,E,150020.000,A,D*4D

The first record is wrong. All other times are around 15xxxx. And all the ones with 16xxxx have .02
