### ISSUE TITLE
NMEA0183 XDR

### ISSUE THREAD

**Issue by chrischanHH** [wellenvogel/esp32-nmea2000#47]
Hi, 
I use the ATOM CANBus Kit with RP4 and AvNav headless and I miss the data on N2K side for Roll and Pitch. In the version discription 20220403 there I can find XDR but at the [Data] side I can't find a cell for this data and on the N2K bus I get no pitch/roll data. Is this a missunderstand of XDR myself or is there missing a part of implementation? In SK I can log following -> @signalk/signalk-to-nmea0183 $IIXDR,A,-0.3,D,PTCH,A,-3.4,D,ROLL*58 

(-: Chrischan

**Comment by wellenvogel** [comment]
Did you define appropriate xdrmappings?
See https://github.com/wellenvogel/esp32-nmea2000/blob/master/doc/XdrMappings.md
As xdr is not really standardized you need to define which xdr value should be converted to which n2k pgn/parameter.
The category for pitch and roll is "Attitude" - this will finally create pgn 127257.
You need to define one mapping for roll and one for pitch!
When you are defining the mapping an example xdr record is shown - just compare with the ones you have.
