### ISSUE TITLE
Speed through water

### ISSUE THREAD

**Issue by chrischanHH** [wellenvogel/esp32-nmea2000#49]
Hi Andreas,
I'm not sure about my understand of NMEA0183 and NMEA2000 but I have a VHW from my log but the device do not create the PNG128259 for speed and so I can not get the value at my Raymarine ST70 multi. Is there something missing to get speed data from my log to the NMEA2000 or have I do configure something for this? 
For me it looks okay ->
![VHW](https://user-images.githubusercontent.com/117594118/221673860-1044b9f8-87da-4816-ad77-4cd66bbee2b8.PNG)
and I can see the speed through water at the data side ->
![stw](https://user-images.githubusercontent.com/117594118/221673997-4aa2e0a4-3827-45f3-8f98-da95f17792dc.PNG)

(-: Chrischan

**Comment by chrischanHH** [comment]
And it seems that the NMEA0183 MTW do not read/convert in the mstack, because I can see at [Status] the receiving MTW messages but in [Data] there is a the field WTemp only '---' and on the NMEA2000 side the is no data too.

**Comment by wellenvogel** [comment]
https://github.com/wellenvogel/esp32-nmea2000/releases/tag/20230309
