### ISSUE TITLE
GwConfigDefinitions.h is missing

### ISSUE THREAD

**Issue by SailorJos** [wellenvogel/esp32-nmea2000#54]
Please add GwConfigDefinitions.h to the files suppied. Thanks.

**Comment by wellenvogel** [comment]
Could you please describe your problem?
The file is generated during the build.

**Comment by SailorJos** [comment]
I tried compiling with ArduinoIDE, which failed due to missing files.
Now I tried PlatformIO (which is new for me) and I can load it in a ESP32. 

So first steps taken. To be continued...

Sorry for the inconvenience. Please close this issue.

**Comment by wellenvogel** [comment]
Best luck & have fun..
