### ISSUE TITLE
NMEA2000-Gateway-MultiHUB

### ISSUE THREAD

**Issue by oxbown** [wellenvogel/esp32-nmea2000#58]
Hi!
I've got an idea to expand the possibilities of NMEA2000-Gateway. M5Stack has a product to expand ATOM ports "[ATOMIC PortABC Extension Base](https://shop.m5stack.com/products/atomic-portabc-extension-base?variant=43894734979329)"
With that module, we could connect several devices to the atom or atoms3 (compatible with both boards). CAN bus, RS485, Serial TTL, and i2C could be connected at the same time.
This is an example of the idea:
![image](https://github.com/wellenvogel/esp32-nmea2000/assets/5922155/48424c6d-8f90-4ca9-b81b-c746e69601a2)

**Comment by wellenvogel** [comment]
Looks like a cool piece.
With the new approach of customized builds this could be integrated.
But we need someone to test this...

**Comment by oxbown** [comment]
I´m going to buy the Hub when it is available in [Mouser Electronics](https://www.mouser.es/ProductDetail/170-A130)
My plan is to make a GATEWAY-SUPER-BOX-IP67 🤣  with all of that hardware inside.

**Comment by oxbown** [comment]
Working on the idea...
![telegram-cloud-photo-size-4-6046420986573733261-y](https://github.com/wellenvogel/esp32-nmea2000/assets/5922155/3d04fd27-1ed4-4230-b8e9-0dd09ff47b10)

**Comment by wellenvogel** [comment]
https://github.com/wellenvogel/esp32-nmea2000/releases/tag/20240324
