### ISSUE TITLE
TCP nmea0183 data not shown on "Data" tab.

### ISSUE THREAD

**Issue by oxbown** [wellenvogel/esp32-nmea2000#64]
Nmea0183 messages sent to the esp32´s TCP server are well received but not show on the webpage Data tab.

**Comment by wellenvogel** [comment]
NMEA messages are never shown at the data tab ;-)
Only converted data items are shown. So there only will be data if you enable the conversion to n2k from the TCP server.

**Comment by oxbown** [comment]
OK, resolved! You are the best!
