### ISSUE TITLE
Stop access point time not working

### ISSUE THREAD

**Issue by norbert-walter** [wellenvogel/esp32-nmea2000#77]
When  I using a stopAPTime grater than 0 the AP will not stop. I see allways the WiFi SSID on air. The device is not connected with anything other devices. Also not as WiFi client.

**Comment by free-x** [comment]
I can partly confirm this behavior. After set to 5 minutes, AP becomes "hidden" flag, but AP is not really stopped

**Comment by wellenvogel** [comment]
I cannot confirm this.
Which version did you run?
I tested it using the latest version (dev build) 20240429 - directly on an M5-Atom with CAN base, setting to 2 minutes.
Did not run Wifi scans...
When using logging you can see something like:

LOG:1814:GWWIFI: AP auto shutdown enabled (120s)
....
GWSERIAL:121815:GWWIFI: shutdown AP

And afterwards the AP cannot be found any more when scanning wifi.

**Comment by norbert-walter** [comment]
Thats the last build on OBP60 and not on a M5Stack.

**Comment by wellenvogel** [comment]
In the UI you set minutes ;-).
Can you provide the logs? Especially the first line about auto shutdown enabled gives you the time.
Most probably I will add a log to write out the number of connected clients - I would suspect that there is still some client being connected.

**Comment by norbert-walter** [comment]
Ohh shit. My problem. Sorry for the misstake.
