### ISSUE TITLE
Larger check boxes on Web page

### ISSUE THREAD

**Issue by norbert-walter** [wellenvogel/esp32-nmea2000#8]
The size of check boxes on the Web page is for larger fingers not practicable. A bigger size of check boxes are helpfully.

**Comment by wellenvogel** [comment]
On which device did you test this? I'm testing on my mobile phone - and it easily works. Bigger buttons/selects are possible but would make the page a bit more hard to use.

**Comment by wellenvogel** [comment]
Closing this due to no further activity.
