### ISSUE TITLE
actisense nmea reader timeout

### ISSUE THREAD

**Issue by CGZ127** [wellenvogel/esp32-nmea2000#80]
Hello,
    I'm using ATMO LITE+ATOM CANBUS,flash m5stack-atom-20240428-all.bin,and change usb mode to actisense, but using the nmea reader software the log shows the get operating mode timeout, I wonder if anything wrong or the board chip changes, could you help me find out?Thanks!
![图片](https://github.com/user-attachments/assets/ceb3be52-03c8-4732-8474-f69b83eb747d)
![图片](https://github.com/user-attachments/assets/b2b0b2eb-0779-4a02-aa6b-29e9d85b7693)
![图片](https://github.com/user-attachments/assets/8a06d361-548b-4de4-9c6d-53c119a0c864)

**Comment by CGZ127** [comment]
I have tried，the default baudrate is 115200 after flashing ,not working，I've tried from 4800 to 115200, none of them can work



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/01/2024 17:42 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [wellenvogel/esp32-nmea2000] actisense nmea reader timeout (Issue #80) |

At First, Set baudrate to 115200 or 230400

Regards
free-x

**Comment by wellenvogel** [comment]
I don't think that you can use any actisense tool to communicate.
Although data will be send on the USB port in actisense format the device does not support the full actisense Protocol.
Especially it will not receive/send any of the control messages.
Using it with other Software that reads/sends data in actisense format should be fine.

**Comment by CGZ127** [comment]
hello again, I just got a usb2can, I was trying sending a HDT sentence by serial to atom ,but nothing can received by the usb2can,and the monitor webpage shows nmea2000 offline, the serial debug dialog shows nvs_open failed, I don't know if this is the problem
<img width="368" alt="屏幕截图 2024-10-03 161854" src="https://github.com/user-attachments/assets/db00c12a-1bb4-4a56-a51c-4b1e7379f12a">
<img width="266" alt="屏幕截图 2024-10-03 161948" src="https://github.com/user-attachments/assets/61717ae2-bda1-497e-ab8f-841612786a0f">
<img width="387" alt="屏幕截图 2024-10-03 162027" src="https://github.com/user-attachments/assets/d018b201-f524-4788-a3ee-25287646e710">
![图片](https://github.com/user-attachments/assets/f944e3db-a516-48b3-a5f2-770c8856987f)

**Comment by wellenvogel** [comment]
For sure you miss a ground connection and bus termination resistors.
But I have no idea on usb2can - i.e. which software you use to connect to it, which protocols it supports...

**Comment by CGZ127** [comment]
I had connected the gnd cable and the 120r terminal resistor is built in the usb2can，the software is pcan view，a canbus monitor software can catch & display raw data on canbus，if the error shows in the debug dialog doesn't matter, I'm considering if the 3035 can bus transceiver is broken.....



---- Replied Message ----
| From | Andreas ***@***.***> |
| Date | 10/03/2024 17:47 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [wellenvogel/esp32-nmea2000] actisense nmea reader timeout (Issue #80) |

For sure you miss a ground connection and bus termination resistors.
But I have no idea on usb2can - i.e. which software you use to connect to it, which protocols it supports...

**Comment by wellenvogel** [comment]
The log about nvs should not matter.

**Comment by wellenvogel** [comment]
As there is no further input I will close the issue.
