### ISSUE TITLE
Converting MTW from PGN130311

### ISSUE THREAD

**Issue by free-x** [wellenvogel/esp32-nmea2000#83]
Hi @wellenvogel ,

Raymarine ST<->STNG Converter sends watertemperature over PGN 130311.
We need enhancement of Handle130311 to create MTW from this PGN

Greetings from Med, where watertemperature +23C is
free-x

**Comment by wellenvogel** [comment]
https://github.com/wellenvogel/esp32-nmea2000/releases/tag/20241114
