### ISSUE TITLE
Naming of Configuration Export File

### ISSUE THREAD

**Issue by W-Geronius** [wellenvogel/esp32-nmea2000#87]
Nice to have:
at present OBP60 V1 device configuration files are called nodemcu32s_obp60_timesstamp.json, OBP60 V2 calls them obp60_s3_timestamp.json
'System Name' as part of the backup file name would be a good candidate to keep backups apart when multiple devices are installed.

**Comment by wellenvogel** [comment]
https://github.com/wellenvogel/esp32-nmea2000/releases/tag/20241114
