### ISSUE TITLE
OTA Firmware full Update failing: missing magic byte

### ISSUE THREAD

**Issue by W-Geronius** [wellenvogel/esp32-nmea2000#89]
Updating the firmware by selecting a xxx-all.bin always fails displaying an error 'missing magic byte at ...'
Updating the firmware by selecting a xxx-upate.bin never fails.

 -all.bin file apears to be checked like a -update.bin file (example using norbert-walter/esp32-nmea2000-obp60/releases/download/20241006/obp60_s3-dev20241006-all.bin)

![CAPT-20241019-140442r](https://github.com/user-attachments/assets/87282e1e-1e3b-4828-9bba-17cb588b3b4f)

At position 288 (0x0120) of a xxx-all.bin file the magix byte can't be found - checkImage should inspect position 65824 (0x010120)
All magic bytes start there:
![CAPT-20241019-144111](https://github.com/user-attachments/assets/c058af69-c36f-40c1-84be-4ce7da9e74e2)

**Comment by wellenvogel** [comment]
You cannot flash an ...all.bin with OTA (what would be the use case for it?).
This is only intended for initial flash via the WebFlasher or esptool.

**Comment by W-Geronius** [comment]
Ok, that wasn't clear (to me) from the documentation. I will suggest to include that hint in Norbert's document.
The issue may be closed, thanks
