### ISSUE TITLE
include time in auto-generated Version number

### ISSUE THREAD

**Issue by TobiasE-github** [wellenvogel/esp32-nmea2000#92]
Suggestion: Change Line 478 of extra_script.py  from
`version="dev"+datetime.now().strftime("%Y%m%d")`
to : 
`version="dev"+datetime.now().strftime("%Y%m%d-%H%M")`

This is beneficial when compiling and testing multiple versions a day.

**Comment by wellenvogel** [comment]
This would mean to recompile everything on each compile call.
This would dramatically increase the cycle time during development.
Most probably the best idea would be to reorganize the version hangling a bit an use a separate cpp for the version info that will be generated.
But I'm not sure if it is worse the effort.
You still can go for a buildflag GWRELEASEVERSION.
