### ISSUE TITLE
Enable GPS to N2K Timer

### ISSUE THREAD

**Issue by hwater** [wellenvogel/esp32-nmea2000#93]
When trying to use the internal GPS (obp60v2 or others) i get only sporadic Outputs via SignalK via Can out (129025).

I want to use the newer GPS from OBP60 as it is more sensitive. So please let us define also an timer how often it goes to can-out. 
Now only the pgn 129540 pings out every second. This is perfect but should also be configurable. 

Maybe all this should go into an obp60-task, but i think the output of the PGNs should be configurable globaly on an page with checkboxes and timers for the sensors. 

I Like your Work - Holger

**Comment by wellenvogel** [comment]
Basically the converter sends out the N2K message whenever the corresponding NMEA0183 message is received - beside the min2KInterval (default 50ms).
For the data that is directly read by the OBP60 this is handled in the OBP60 code. So if you feel that the data should be send at a different interval you should create an issue there.
